# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet Another Dev Blog
email: m.romanutti@gmail.com
description: >
  Articles along my path as software developer. Covers architectures, frameworks, paradigms and more!
logo: "/assets/images/mr.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Marco Romanutti'
bio: >
  Passionate software engineer with a double degree in computer
  science and business information systems and experience using
  different technology stacks. Equally passionate about cycling.
author_image: "/assets/images/author.jpg"
twitter_username: romanutti
github_username:  romanutti

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
